#!/bin/bash
# Script to create GitHub issues from todo.md
# This script is generated by sync-todo-to-github.py
# 
# Prerequisites:
# - GitHub CLI (gh) must be installed
# - You must be authenticated (run: gh auth login)
# - You must have write access to the repository
#
# Usage:
#   ./scripts/create-github-issues.sh [--dry-run]
#
# Options:
#   --dry-run  Show what would be created without actually creating issues

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TASKS_FILE="$SCRIPT_DIR/todo-tasks.json"
REPO="sbourbousse/Trackly"
DRY_RUN=false

# Parse arguments
if [ "$1" = "--dry-run" ]; then
    DRY_RUN=true
    echo "🔍 DRY RUN MODE - No issues will be created"
    echo ""
fi

# Check if gh is installed
if ! command -v gh &> /dev/null; then
    echo "❌ Error: GitHub CLI (gh) is not installed"
    echo "   Install from: https://cli.github.com/"
    exit 1
fi

# Check if authenticated
if ! gh auth status &> /dev/null; then
    echo "❌ Error: Not authenticated with GitHub CLI"
    echo "   Run: gh auth login"
    exit 1
fi

# Check if tasks file exists
if [ ! -f "$TASKS_FILE" ]; then
    echo "❌ Error: Tasks file not found: $TASKS_FILE"
    echo "   Run: python3 $SCRIPT_DIR/sync-todo-to-github.py"
    exit 1
fi

# Read number of tasks
TASK_COUNT=$(jq length "$TASKS_FILE")
echo "📋 Found $TASK_COUNT tasks to create as issues"
echo ""

# Function to create or ensure label exists
ensure_label() {
    local label_name=$1
    local label_color=$2
    local label_desc=$3
    
    if [ "$DRY_RUN" = true ]; then
        echo "  Would ensure label: $label_name"
        return 0
    fi
    
    # Check if label exists
    if gh label list -R "$REPO" | grep -q "^$label_name"; then
        echo "  ✓ Label already exists: $label_name"
    else
        echo "  + Creating label: $label_name"
        gh label create "$label_name" -R "$REPO" -c "$label_color" -d "$label_desc" || true
    fi
}

# Create necessary labels
echo "🏷️  Ensuring labels exist..."
ensure_label "backend" "0e8a16" "Backend .NET tasks"
ensure_label "frontend" "1d76db" "Frontend tasks"
ensure_label "driver" "5319e7" "Driver app tasks"
ensure_label "business" "bfd4f2" "Business app tasks"
ensure_label "tracking" "d4c5f9" "Tracking app tasks"
ensure_label "integrations" "fbca04" "Third-party integrations"
ensure_label "signalr" "c5def5" "SignalR related tasks"
ensure_label "geolocation" "0075ca" "Geolocation features"
ensure_label "shared" "e99695" "Shared code/types"
ensure_label "types" "f9d0c4" "TypeScript types"
ensure_label "infrastructure" "d93f0b" "Infrastructure/DevOps"
ensure_label "api" "c2e0c6" "API endpoints"
ensure_label "ui" "d876e3" "User interface"
ensure_label "bug" "d73a4a" "Bug fixes"
ensure_label "manual" "fef2c0" "Manual tasks"
ensure_label "priority" "b60205" "High priority"
echo ""

# Create issues
echo "🚀 Creating issues..."
echo ""

# Counter for created issues
created=0
skipped=0

# Read tasks and create issues
for i in $(seq 0 $((TASK_COUNT - 1))); do
    # Extract task data using jq
    task_text=$(jq -r ".[$i].text" "$TASKS_FILE")
    category=$(jq -r ".[$i].category" "$TASKS_FILE")
    subcategory=$(jq -r ".[$i].subcategory // empty" "$TASKS_FILE")
    line_number=$(jq -r ".[$i].line_number" "$TASKS_FILE")
    labels=$(jq -r ".[$i].labels | join(\",\")" "$TASKS_FILE")
    
    # Use task text as title (Python parser already handles truncation)
    title="$task_text"
    
    # Generate body
    body="**Task from todo.md (line $line_number)**

$task_text

**Category:** $category"
    
    if [ -n "$subcategory" ] && [ "$subcategory" != "null" ]; then
        body="$body
**Subcategory:** $subcategory"
    fi
    
    body="$body

---
This issue was automatically created from the todo.md file."
    
    echo "Issue $((i + 1))/$TASK_COUNT: $title"
    echo "  Labels: $labels"
    
    if [ "$DRY_RUN" = true ]; then
        echo "  [DRY RUN] Would create issue"
        ((created++))
    else
        # Create the issue
        if gh issue create -R "$REPO" \
            --title "$title" \
            --body "$body" \
            --label "$labels" > /dev/null 2>&1; then
            echo "  ✓ Created"
            ((created++))
        else
            echo "  ✗ Failed to create (may already exist)"
            ((skipped++))
        fi
    fi
    echo ""
    
    # Small delay to avoid rate limiting
    sleep 0.5
done

echo ""
echo "✅ Summary:"
echo "   Created: $created issues"
if [ $skipped -gt 0 ]; then
    echo "   Skipped: $skipped issues"
fi

if [ "$DRY_RUN" = true ]; then
    echo ""
    echo "ℹ️  This was a dry run. No issues were created."
    echo "   Run without --dry-run to create the issues."
fi
